# Site settings
title: Basel Farah's Personal Site
email: hello@baselfarah.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is the personal site for Basel Farah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.baselfarah.co.uk" # the base hostname & protocol for your site
twitter_username: baself
github_username:  baz44
linkedin_username: baself

# Build settings
markdown: kramdown

# analytics :
#   provider : google
#   google :
#       tracking_id : 'UA-10597908-4'
