# Site settings
title: &lt;i&gt;foo, bar, &lt;strong&gt;Baz&lt;/strong&gt;&lt;&#92;i&gt;
email: hello at baselfarah dot co dot uk
description: > # this means to ignore newlines until "baseurl:"
             Baz description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.baselfarah.co.uk" # the base hostname & protocol for your site
twitter_username: baself
github_username:  baz44
linkedin_username: baself

# Build settings
markdown: kramdown
analytics :
   provider : google
   google :
       tracking_id : 'UA-10597908-4'
